// Generated by 'unplugin-auto-import'
export {}
declare global {
  const MAX_CACHE: typeof import('./utils/cache')['MAX_CACHE']
  const SUPPORTED_MINIFY_MIMES: typeof import('./utils/minify')['SUPPORTED_MINIFY_MIMES']
  const getContentMime: typeof import('./utils/mime')['getContentMime']
  const invalidRequestPath: typeof import('./utils/invalid-request')['invalidRequestPath']
  const minify: typeof import('./utils/minify')['minify']
  const parseGithubURL: typeof import('./utils/parse')['parseGithubURL']
  const parseNPMURL: typeof import('./utils/parse')['parseNPMURL']
  const stringToUint8Array: typeof import('./utils/convert')['stringToUint8Array']
  const uint8ArrayToString: typeof import('./utils/convert')['uint8ArrayToString']
}
